/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BadRequest = {
  /**
   * @description Error message
   * @type string
   */
  message: string
  /**
   * @description Error type
   * @type string
   */
  error: string
  /**
   * @description Error status code
   * @type number
   */
  statusCode: number
}