/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetAccountingSchema } from "./BudgetAccountingSchema";

export type BudgetAccountingDataSchema = {
  /**
   * @type array
   */
  income: BudgetAccountingSchema[];
  /**
   * @type array
   */
  expense: BudgetAccountingSchema[];
};
