/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BudgetAccountingMetaSchema = {
  /**
   * @type object
   */
  total: {
    /**
     * @type number
     */
    income: number
    /**
     * @type number
     */
    expense: number
    /**
     * @type number
     */
    planned_income: number
    /**
     * @type number
     */
    planned_expense: number
  }
  /**
   * @type number
   */
  min_year: number
  /**
   * @type number
   */
  max_year: number
}