/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BudgetAccountingDataSchema } from "./BudgetAccountingDataSchema";
import type { BudgetAccountingMetaSchema } from "./BudgetAccountingMetaSchema";

export type BudgetAccountingResponseSchema = {
  /**
   * @type object
   */
  data: BudgetAccountingDataSchema;
  /**
   * @type object
   */
  meta: BudgetAccountingMetaSchema;
};
