/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateProjectParentTaskBody = {
  /**
   * @description Наименование родительской задачи
   * @minLength 1
   * @type string
   */
  name: string
  /**
   * @description Описание родительской задачи
   * @type string
   */
  description?: string | null
  /**
   * @description Дедлайн родительской задачи
   * @type string
   */
  deadline_date?: string | null
}