/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateTeamBody = {
  /**
   * @description Наименование команды
   * @minLength 1
   * @type string
   */
  name: string
}