/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateEventBody } from './CreateEventBody.ts'

export type CreateEventsBody = {
  /**
   * @description Список событий
   * @type array
   */
  events: CreateEventBody[]
}