/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateProjectColumnBody = {
  /**
   * @description Название столбца
   * @type string
   */
  name: string
  /**
   * @description Признак удаления столбца
   * @type boolean
   */
  is_removable?: boolean | null
  /**
   * @description Признак разрешения создания задач в столбце
   * @type boolean
   */
  is_task_creation_allowed?: boolean | null
  /**
   * @description Признак столбца финального этапа
   * @type boolean
   */
  is_final_stage?: boolean | null
}