/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateProjectBody = {
  /**
   * @description Название проекта
   * @minLength 1
   * @type string
   */
  name: string
}