/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GoalBodyTask } from "./GoalBodyTask";

export type CreateGoalBody = {
  /**
   * @description Заголовок цели
   * @type string
   */
  title: string;
  /**
   * @description Категория цели
   * @type string
   */
  category: string;
  /**
   * @description Дата окончания цели
   * @type string | undefined
   */
  deadline_date?: string;
  /**
   * @description Примечание к цели
   * @type string | undefined
   */
  note?: string;
  /**
   * @description Задачи цели
   * @type array
   */
  tasks?: GoalBodyTask[] | null;
};
