/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteTeamMembersBody = {
  /**
   * @description ID участников команды
   * @type array
   */
  member_ids: number[]
}