/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type EventDto = {
  /**
   * @description ID события
   * @type number
   */
  id: number
  /**
   * @description Заголовок события
   * @type string
   */
  title: string
  /**
   * @description Время начала события
   * @type number
   */
  start_timestamp: number
  /**
   * @description Время окончания события
   * @type number
   */
  end_timestamp: number
}