/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProjectDto } from "./ProjectDto";

export type GeneralInfoProjectDto = {
  /**
   * @type array
   */
  upcoming_deadline: ProjectDto[];
  /**
   * @type array
   */
  assigned_me: ProjectDto[];
};
