/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GoalWithoutTasksDto = {
  /**
   * @description ID цели
   * @type number
   */
  id: number
  /**
   * @description Заголовок цели
   * @type string
   */
  title: string
  /**
   * @description Категория цели
   * @type string
   */
  category: string
  /**
   * @description Статус цели
   * @type string
   */
  status: string
  /**
   * @description Дата окончания цели
   * @type string
   */
  deadline_date?: string | null
  /**
   * @description Примечание к цели
   * @type string
   */
  note?: string | null
  /**
   * @description Дата выполнения цели
   * @type string
   */
  achieved_date?: string | null
}