/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TaskDto } from './TaskDto.ts'

export type GoalDto = {
  /**
   * @description ID цели
   * @type number
   */
  id: number
  /**
   * @description Заголовок цели
   * @type string
   */
  title: string
  /**
   * @description Категория цели
   * @type string
   */
  category: string
  /**
   * @description Статус цели
   * @type string
   */
  status: string
  /**
   * @description Дата окончания цели
   * @type string | undefined
   */
  deadline_date?: string
  /**
   * @description Примечание к цели
   * @type string | undefined
   */
  note?: string
  /**
   * @description Дата выполнения цели
   * @type string | undefined
   */
  achieved_date?: string
  /**
   * @description Задачи цели
   * @type array
   */
  tasks?: TaskDto[] | null
}