/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GoalBodyTask = {
  /**
   * @description ID задачи
   * @type number | undefined
   */
  id?: number
  /**
   * @description Заголовок задачи
   * @minLength 1
   * @type string
   */
  title: string
  /**
   * @description Дата окончания задачи
   * @type string | undefined
   */
  deadline_date?: string
  /**
   * @description Примечание задачи
   * @type string | undefined
   */
  note?: string
  /**
   * @description Дата выполнения задачи
   * @type string | undefined
   */
  done_date?: string
}