/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type InviteUserBody = {
  /**
   * @description ID приглашения пользователя
   * @type string
   */
  user_invite_id: string
  /**
   * @description ID команды
   * @type number
   */
  team_id: number
}