/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserDto } from "./UserDto";

export type MemberDto = {
  /**
   * @description ID участника
   * @type number
   */
  id: number;
  /**
   * @description Данные пользователя
   */
  user: UserDto;
  /**
   * @description Роль в команде
   * @type string
   */
  role: string;
};
