/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProjectRightsDto } from "./ProjectRightsDto";
import type { UserDto } from "./UserDto";

export type MemberDto = {
  /**
   * @description ID участника
   * @type number
   */
  id: number;
  /**
   * @description Данные пользователя
   */
  user: UserDto;
  /**
   * @description Роль в команде
   * @type string
   */
  role: string;
  /**
   * @description Массив прав в проектах
   * @type array | undefined
   */
  projects_rights?: ProjectRightsDto[];
};
