/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type NotificationDto = {
  /**
   * @description ID уведомления
   * @type number
   */
  id: number
  /**
   * @description Заголовок уведомления
   * @type string
   */
  title: string
  /**
   * @description Описание уведомления
   * @type string | undefined
   */
  description?: string
  /**
   * @description Ссылка на принятие уведомления
   * @type string | undefined
   */
  accept?: string
  /**
   * @description Ссылка на отклонение уведомления
   * @type string | undefined
   */
  reject?: string
}