/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProjectColumn = {
  /**
   * @description ID столбца проекта
   * @type string
   */
  id: string
  /**
   * @description Название столбца
   * @type string
   */
  name: string
  /**
   * @description Порядковый номер столбца
   * @type number
   */
  order: number
  /**
   * @description Признак удаления столбца
   * @type boolean
   */
  removable?: boolean | null
}