/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TeamDto } from "./TeamDto";

export type ProjectDto = {
  /**
   * @description ID проекта
   * @type number
   */
  id: number;
  /**
   * @description Название проекта
   * @type string
   */
  name: string;
  /**
   * @description Команда проекта
   */
  team: TeamDto;
};
