/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ProjectRightsDto = {
  /**
   * @description ID проекта
   * @type number
   */
  project_id: number
  /**
   * @description Создание
   * @type boolean
   */
  create: boolean
  /**
   * @description Чтение
   * @type boolean
   */
  read: boolean
  /**
   * @description Обновление
   * @type boolean
   */
  update: boolean
  /**
   * @description Удаление
   * @type boolean
   */
  delete: boolean
}