/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MemberDto } from "./MemberDto";
import type { ProjectColumn } from "./ProjectColumn";

export type ProjectTaskDto = {
  /**
   * @description ID задачи
   * @type number
   */
  id: number;
  /**
   * @description Наименование задачи
   * @type string
   */
  name: string;
  /**
   * @description Описание задачи
   * @type string
   */
  description?: string | null;
  /**
   * @description Столбец задачи
   */
  column: ProjectColumn;
  /**
   * @description Приоритет задачи
   * @type string
   */
  priority?: string | null;
  /**
   * @description Автор задачи
   */
  author: MemberDto;
  /**
   * @description Исполнитель задачи
   */
  executor?: MemberDto | null;
  /**
   * @description Дедлайн задачи
   * @type string
   */
  deadline_date?: string | null;
  /**
   * @description Дата завершения задачи
   * @type string
   */
  done_date?: string | null;
};
