/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type ShortInfoProjectDto = {
  /**
   * @description ID проекта
   * @type number
   */
  id: number
  /**
   * @description Название проекта
   * @type string
   */
  name: string
}