/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GoalWithoutTasksDto } from "./GoalWithoutTasksDto";

export type TaskDto = {
  /**
   * @description ID задачи
   * @type number
   */
  id: number;
  /**
   * @description Заголовок задачи
   * @type string
   */
  title: string;
  /**
   * @description Дата окончания задачи
   * @type string
   */
  deadline_date?: string | null;
  /**
   * @description Примечание задачи
   * @type string
   */
  note?: string | null;
  /**
   * @description Дата выполнения задачи
   * @type string
   */
  done_date?: string | null;
  /**
   * @description Цель, к которой относится задача
   */
  goal?: GoalWithoutTasksDto;
};
