/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TeamGeneralInfoDto = {
  /**
   * @description ID команды
   * @type number
   */
  id: number
  /**
   * @description Наименование команды
   * @type string
   */
  name: string
  /**
   * @description Количество участников команды
   * @type number
   */
  members_length: number
}