/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MemberDto } from "./MemberDto";

export type TeamDto = {
  /**
   * @description ID команды
   * @type number
   */
  id: number;
  /**
   * @description Наименование команды
   * @type string
   */
  name: string;
  /**
   * @description Роль пользователя в команде
   * @type string
   */
  user_role: string;
  /**
   * @description Участники команды
   * @type array
   */
  members: MemberDto[];
};
