/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProjectRightsDto } from "./ProjectRightsDto";

export type UpdateTeamMemberBody = {
  /**
   * @description Роль участника команды
   * @minLength 1
   * @type string
   */
  role: string;
  /**
   * @description Массив прав в проектах
   * @type array | undefined
   */
  projects_rights?: ProjectRightsDto[];
};
