/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateProjectTaskListOrderBody = {
  /**
   * @description ID задачи
   * @type number
   */
  id: number
  /**
   * @description Порядок задачи в списке
   * @type number
   */
  list_order: number
}