/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ProjectColumn } from "./ProjectColumn";

export type UpdateProjectBody = {
  /**
   * @description Название проекта
   * @type string
   */
  name?: string | null;
  /**
   * @description Описание проекта
   * @type array
   */
  columns?: ProjectColumn[] | null;
};
