/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GoalBodyTask } from "./GoalBodyTask";

export type UpdateGoalBody = {
  /**
   * @description Заголовок цели
   * @type string | undefined
   */
  title?: string;
  /**
   * @description Категория цели
   * @type string | undefined
   */
  category?: string;
  /**
   * @description Статус цели
   * @type string | undefined
   */
  status?: string;
  /**
   * @description Дата окончания цели
   * @type string
   */
  deadline_date?: string | null;
  /**
   * @description Примечание к цели
   * @type string
   */
  note?: string | null;
  /**
   * @description Дата выполнения цели
   * @type string
   */
  achieved_date?: string | null;
  /**
   * @description Задачи цели
   * @type array
   */
  tasks?: GoalBodyTask[] | null;
};
