/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateTaskListOrderBody = {
  /**
   * @description ID задачи
   * @type number
   */
  id: number
  /**
   * @description Порядок задачи в списке доски
   * @type number
   */
  list_order: number
}