/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateGoalListOrderBody = {
  /**
   * @description ID цели
   * @type number
   */
  id: number
  /**
   * @description Порядок цели в списке
   * @type number
   */
  list_order: number
}