/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UserDto = {
  /**
   * @description ID пользователя
   * @type number
   */
  id: number
  /**
   * @description Имя пользователя
   * @type string
   */
  username: string
  /**
   * @description Email пользователя
   * @type string
   */
  email: string
  /**
   * @description Изображение пользователя
   * @type string
   */
  picture_url: string
}