/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { userDtoSchema } from "../userDtoSchema";
import { z } from "zod";

export const getUser200Schema = z.lazy(() => userDtoSchema);

export type GetUser200Schema = z.infer<typeof getUser200Schema>;

export const getUser404Schema = z.lazy(() => badRequestSchema);

export type GetUser404Schema = z.infer<typeof getUser404Schema>;

export const getUserQueryResponseSchema = z.lazy(() => getUser200Schema);

export type GetUserQueryResponseSchema = z.infer<
  typeof getUserQueryResponseSchema
>;
