/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from "@/shared/api/axios-client";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/axios-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetUserQueryResponse,
  GetUser404,
} from "../../models/users/GetUser";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getUserQueryKey = () => [{ url: "/users/user" }] as const;

export type GetUserQueryKey = ReturnType<typeof getUserQueryKey>;

/**
 * @summary Get user
 * {@link /users/user}
 */
export async function getUser(
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    GetUserQueryResponse,
    ResponseErrorConfig<GetUser404>,
    unknown
  >({ method: "GET", url: `/users/user`, ...requestConfig });
  return res.data;
}

export function getUserQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getUserQueryKey();
  return queryOptions<
    GetUserQueryResponse,
    ResponseErrorConfig<GetUser404>,
    GetUserQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getUser(config);
    },
  });
}

/**
 * @summary Get user
 * {@link /users/user}
 */
export function useGetUser<
  TData = GetUserQueryResponse,
  TQueryData = GetUserQueryResponse,
  TQueryKey extends QueryKey = GetUserQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetUserQueryResponse,
        ResponseErrorConfig<GetUser404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getUserQueryKey();

  const query = useQuery(
    {
      ...(getUserQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, "queryKey">),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetUser404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
