/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { createEventsBodySchema } from "../createEventsBodySchema";
import { eventDtoSchema } from "../eventDtoSchema";
import { z } from "zod";

export const createEvents200Schema = z.array(z.lazy(() => eventDtoSchema));

export type CreateEvents200Schema = z.infer<typeof createEvents200Schema>;

export const createEvents400Schema = z.lazy(() => badRequestSchema);

export type CreateEvents400Schema = z.infer<typeof createEvents400Schema>;

export const createEventsMutationRequestSchema = z.lazy(
  () => createEventsBodySchema,
);

export type CreateEventsMutationRequestSchema = z.infer<
  typeof createEventsMutationRequestSchema
>;

export const createEventsMutationResponseSchema = z.lazy(
  () => createEvents200Schema,
);

export type CreateEventsMutationResponseSchema = z.infer<
  typeof createEventsMutationResponseSchema
>;
