/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from "@/shared/api/axios-client";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/axios-client";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type {
  CreateTeamMutationRequest,
  CreateTeamMutationResponse,
  CreateTeam400,
} from "../../models/teams/CreateTeam";
import { useMutation } from "@tanstack/react-query";
import {
  createTeamMutationResponseSchema,
  createTeamMutationRequestSchema,
} from "../../zod/teams/createTeamSchema";

export const createTeamMutationKey = () => [{ url: "/teams" }] as const;

export type CreateTeamMutationKey = ReturnType<typeof createTeamMutationKey>;

/**
 * @summary Create team
 * {@link /teams}
 */
export async function createTeam(
  { data }: { data: CreateTeamMutationRequest },
  config: Partial<RequestConfig<CreateTeamMutationRequest>> & {
    client?: typeof client;
  } = {},
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    CreateTeamMutationResponse,
    ResponseErrorConfig<CreateTeam400>,
    CreateTeamMutationRequest
  >({
    method: "POST",
    url: `/teams`,
    data: createTeamMutationRequestSchema.parse(data),
    ...requestConfig,
  });
  return createTeamMutationResponseSchema.parse(res.data);
}

/**
 * @summary Create team
 * {@link /teams}
 */
export function useCreateTeam<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateTeamMutationResponse,
      ResponseErrorConfig<CreateTeam400>,
      { data: CreateTeamMutationRequest },
      TContext
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig<CreateTeamMutationRequest>> & {
      client?: typeof client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createTeamMutationKey();

  return useMutation<
    CreateTeamMutationResponse,
    ResponseErrorConfig<CreateTeam400>,
    { data: CreateTeamMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return createTeam({ data }, config);
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  );
}
