/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { ProfileDto } from "../ProfileDto";

export type GetProfile200 = ProfileDto;

export type GetProfile404 = BadRequest;

export type GetProfileQueryResponse = GetProfile200;

export type GetProfileQuery = {
  Response: GetProfile200;
  Errors: GetProfile404;
};
