/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { UserDto } from "../UserDto";

export type GetProfile200 = UserDto;

/**
 * @description Пользователь не найден
 */
export type GetProfile404 = BadRequest;

export type GetProfileQueryResponse = GetProfile200;

export type GetProfileQuery = {
  Response: GetProfile200;
  Errors: GetProfile404;
};
