/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { generalInfoProjectDtoSchema } from "../generalInfoProjectDtoSchema";
import { z } from "zod";

export const getProjectsGeneralInfoQueryParamsSchema = z.object({
  team_id: z.coerce.number(),
});

export type GetProjectsGeneralInfoQueryParamsSchema = z.infer<
  typeof getProjectsGeneralInfoQueryParamsSchema
>;

export const getProjectsGeneralInfo200Schema = z.lazy(
  () => generalInfoProjectDtoSchema,
);

export type GetProjectsGeneralInfo200Schema = z.infer<
  typeof getProjectsGeneralInfo200Schema
>;

export const getProjectsGeneralInfo400Schema = z.lazy(() => badRequestSchema);

export type GetProjectsGeneralInfo400Schema = z.infer<
  typeof getProjectsGeneralInfo400Schema
>;

export const getProjectsGeneralInfoQueryResponseSchema = z.lazy(
  () => getProjectsGeneralInfo200Schema,
);

export type GetProjectsGeneralInfoQueryResponseSchema = z.infer<
  typeof getProjectsGeneralInfoQueryResponseSchema
>;
