/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { projectColumnSchema } from "../projectColumnSchema";
import { projectDtoSchema } from "../projectDtoSchema";
import { z } from "zod";

export const updateProjectColumnPathParamsSchema = z.object({
  column_id: z.string(),
  project_id: z.coerce.number(),
});

export type UpdateProjectColumnPathParamsSchema = z.infer<
  typeof updateProjectColumnPathParamsSchema
>;

export const updateProjectColumn200Schema = z.lazy(() => projectDtoSchema);

export type UpdateProjectColumn200Schema = z.infer<
  typeof updateProjectColumn200Schema
>;

export const updateProjectColumn400Schema = z.lazy(() => badRequestSchema);

export type UpdateProjectColumn400Schema = z.infer<
  typeof updateProjectColumn400Schema
>;

export const updateProjectColumnMutationRequestSchema = z.lazy(
  () => projectColumnSchema,
);

export type UpdateProjectColumnMutationRequestSchema = z.infer<
  typeof updateProjectColumnMutationRequestSchema
>;

export const updateProjectColumnMutationResponseSchema = z.lazy(
  () => updateProjectColumn200Schema,
);

export type UpdateProjectColumnMutationResponseSchema = z.infer<
  typeof updateProjectColumnMutationResponseSchema
>;
