/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createProjectParentTaskBodySchema = z.object({
  name: z.string().min(1).describe('Наименование родительской задачи'),
  description: z.string().describe('Описание родительской задачи').nullable().nullish(),
  deadline_date: z.string().describe('Дедлайн родительской задачи').nullable().nullish(),
})

export type CreateProjectParentTaskBodySchema = z.infer<typeof createProjectParentTaskBodySchema>