/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { createProjectTaskBodySchema } from "../createProjectTaskBodySchema";
import { projectTaskDtoSchema } from "../projectTaskDtoSchema";
import { z } from "zod";

export const createProjectTaskPathParamsSchema = z.object({
  project_id: z.coerce.number(),
});

export type CreateProjectTaskPathParamsSchema = z.infer<
  typeof createProjectTaskPathParamsSchema
>;

export const createProjectTask200Schema = z.lazy(() => projectTaskDtoSchema);

export type CreateProjectTask200Schema = z.infer<
  typeof createProjectTask200Schema
>;

export const createProjectTask400Schema = z.lazy(() => badRequestSchema);

export type CreateProjectTask400Schema = z.infer<
  typeof createProjectTask400Schema
>;

export const createProjectTaskMutationRequestSchema = z.lazy(
  () => createProjectTaskBodySchema,
);

export type CreateProjectTaskMutationRequestSchema = z.infer<
  typeof createProjectTaskMutationRequestSchema
>;

export const createProjectTaskMutationResponseSchema = z.lazy(
  () => createProjectTask200Schema,
);

export type CreateProjectTaskMutationResponseSchema = z.infer<
  typeof createProjectTaskMutationResponseSchema
>;
