/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { createProjectColumnBodySchema } from "../createProjectColumnBodySchema";
import { projectColumnSchema } from "../projectColumnSchema";
import { z } from "zod";

export const createProjectColumnPathParamsSchema = z.object({
  project_id: z.coerce.number(),
});

export type CreateProjectColumnPathParamsSchema = z.infer<
  typeof createProjectColumnPathParamsSchema
>;

export const createProjectColumn200Schema = z.lazy(() => projectColumnSchema);

export type CreateProjectColumn200Schema = z.infer<
  typeof createProjectColumn200Schema
>;

export const createProjectColumn400Schema = z.lazy(() => badRequestSchema);

export type CreateProjectColumn400Schema = z.infer<
  typeof createProjectColumn400Schema
>;

export const createProjectColumnMutationRequestSchema = z.lazy(
  () => createProjectColumnBodySchema,
);

export type CreateProjectColumnMutationRequestSchema = z.infer<
  typeof createProjectColumnMutationRequestSchema
>;

export const createProjectColumnMutationResponseSchema = z.lazy(
  () => createProjectColumn200Schema,
);

export type CreateProjectColumnMutationResponseSchema = z.infer<
  typeof createProjectColumnMutationResponseSchema
>;
