/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { projectTaskDtoSchema } from "../projectTaskDtoSchema";
import { z } from "zod";

export const deleteProjectTaskPathParamsSchema = z.object({
  task_id: z.coerce.number(),
  project_id: z.string(),
});

export type DeleteProjectTaskPathParamsSchema = z.infer<
  typeof deleteProjectTaskPathParamsSchema
>;

export const deleteProjectTask200Schema = z.lazy(() => projectTaskDtoSchema);

export type DeleteProjectTask200Schema = z.infer<
  typeof deleteProjectTask200Schema
>;

export const deleteProjectTask400Schema = z.lazy(() => badRequestSchema);

export type DeleteProjectTask400Schema = z.infer<
  typeof deleteProjectTask400Schema
>;

export const deleteProjectTaskMutationResponseSchema = z.lazy(
  () => deleteProjectTask200Schema,
);

export type DeleteProjectTaskMutationResponseSchema = z.infer<
  typeof deleteProjectTaskMutationResponseSchema
>;
