/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { projectDtoSchema } from "../projectDtoSchema";
import { z } from "zod";

export const deleteProjectPathParamsSchema = z.object({
  project_id: z.string(),
});

export type DeleteProjectPathParamsSchema = z.infer<
  typeof deleteProjectPathParamsSchema
>;

export const deleteProject200Schema = z.lazy(() => projectDtoSchema);

export type DeleteProject200Schema = z.infer<typeof deleteProject200Schema>;

export const deleteProject400Schema = z.lazy(() => badRequestSchema);

export type DeleteProject400Schema = z.infer<typeof deleteProject400Schema>;

export const deleteProjectMutationResponseSchema = z.lazy(
  () => deleteProject200Schema,
);

export type DeleteProjectMutationResponseSchema = z.infer<
  typeof deleteProjectMutationResponseSchema
>;
