/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { projectColumnSchema } from "../projectColumnSchema";
import { z } from "zod";

export const deleteProjectColumnPathParamsSchema = z.object({
  column_id: z.string(),
  project_id: z.coerce.number(),
});

export type DeleteProjectColumnPathParamsSchema = z.infer<
  typeof deleteProjectColumnPathParamsSchema
>;

export const deleteProjectColumn200Schema = z.lazy(() => projectColumnSchema);

export type DeleteProjectColumn200Schema = z.infer<
  typeof deleteProjectColumn200Schema
>;

export const deleteProjectColumn400Schema = z.lazy(() => badRequestSchema);

export type DeleteProjectColumn400Schema = z.infer<
  typeof deleteProjectColumn400Schema
>;

export const deleteProjectColumnMutationResponseSchema = z.lazy(
  () => deleteProjectColumn200Schema,
);

export type DeleteProjectColumnMutationResponseSchema = z.infer<
  typeof deleteProjectColumnMutationResponseSchema
>;
