/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { projectDtoSchema } from "../projectDtoSchema";
import { z } from "zod";

export const getProjectPathParamsSchema = z.object({
  project_id: z.string(),
});

export type GetProjectPathParamsSchema = z.infer<
  typeof getProjectPathParamsSchema
>;

export const getProject200Schema = z.lazy(() => projectDtoSchema);

export type GetProject200Schema = z.infer<typeof getProject200Schema>;

export const getProject400Schema = z.lazy(() => badRequestSchema);

export type GetProject400Schema = z.infer<typeof getProject400Schema>;

export const getProjectQueryResponseSchema = z.lazy(() => getProject200Schema);

export type GetProjectQueryResponseSchema = z.infer<
  typeof getProjectQueryResponseSchema
>;
