/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { shortInfoProjectDtoSchema } from "../shortInfoProjectDtoSchema";
import { z } from "zod";

export const getProjectsQueryParamsSchema = z.object({
  team_id: z.string(),
});

export type GetProjectsQueryParamsSchema = z.infer<
  typeof getProjectsQueryParamsSchema
>;

export const getProjects200Schema = z.array(
  z.lazy(() => shortInfoProjectDtoSchema),
);

export type GetProjects200Schema = z.infer<typeof getProjects200Schema>;

export const getProjects400Schema = z.lazy(() => badRequestSchema);

export type GetProjects400Schema = z.infer<typeof getProjects400Schema>;

export const getProjectsQueryResponseSchema = z.lazy(
  () => getProjects200Schema,
);

export type GetProjectsQueryResponseSchema = z.infer<
  typeof getProjectsQueryResponseSchema
>;
