/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { projectTaskDtoSchema } from "../projectTaskDtoSchema";
import { updateProjectTaskBodySchema } from "../updateProjectTaskBodySchema";
import { z } from "zod";

export const updateProjectTaskPathParamsSchema = z.object({
  task_id: z.coerce.number(),
  project_id: z.coerce.number(),
});

export type UpdateProjectTaskPathParamsSchema = z.infer<
  typeof updateProjectTaskPathParamsSchema
>;

export const updateProjectTask200Schema = z.lazy(() => projectTaskDtoSchema);

export type UpdateProjectTask200Schema = z.infer<
  typeof updateProjectTask200Schema
>;

export const updateProjectTask400Schema = z.lazy(() => badRequestSchema);

export type UpdateProjectTask400Schema = z.infer<
  typeof updateProjectTask400Schema
>;

export const updateProjectTaskMutationRequestSchema = z.lazy(
  () => updateProjectTaskBodySchema,
);

export type UpdateProjectTaskMutationRequestSchema = z.infer<
  typeof updateProjectTaskMutationRequestSchema
>;

export const updateProjectTaskMutationResponseSchema = z.lazy(
  () => updateProjectTask200Schema,
);

export type UpdateProjectTaskMutationResponseSchema = z.infer<
  typeof updateProjectTaskMutationResponseSchema
>;
