/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { projectDtoSchema } from "../projectDtoSchema";
import { updateProjectBodySchema } from "../updateProjectBodySchema";
import { z } from "zod";

export const updateProjectPathParamsSchema = z.object({
  project_id: z.coerce.number(),
});

export type UpdateProjectPathParamsSchema = z.infer<
  typeof updateProjectPathParamsSchema
>;

export const updateProject200Schema = z.lazy(() => projectDtoSchema);

export type UpdateProject200Schema = z.infer<typeof updateProject200Schema>;

export const updateProject400Schema = z.lazy(() => badRequestSchema);

export type UpdateProject400Schema = z.infer<typeof updateProject400Schema>;

export const updateProjectMutationRequestSchema = z.lazy(
  () => updateProjectBodySchema,
);

export type UpdateProjectMutationRequestSchema = z.infer<
  typeof updateProjectMutationRequestSchema
>;

export const updateProjectMutationResponseSchema = z.lazy(
  () => updateProject200Schema,
);

export type UpdateProjectMutationResponseSchema = z.infer<
  typeof updateProjectMutationResponseSchema
>;
