/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { ZOD_ERROR } from "@/shared/constants/errors";

export const updateProjectParentTaskSchema = z.object({
  name: z.string(ZOD_ERROR),
  description: z.string(ZOD_ERROR).nullish(),
  deadline_date: z.string(ZOD_ERROR).nullish(),
  done_date: z.string(ZOD_ERROR).nullish(),
  project_task_ids: z.array(z.number(ZOD_ERROR), ZOD_ERROR).nullish(),
});
