/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { ZOD_ERROR } from "@/shared/constants/errors";

export const createProjectBodySchema = z.object({
  name: z
    .string(ZOD_ERROR)
    .nonempty("Заполните поле")
    .describe("Название проекта"),
});

export type CreateProjectBodySchema = z.infer<typeof createProjectBodySchema>;
