/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { ZOD_ERROR } from "@/shared/constants/errors";

export const createTeamBodySchema = z.object({
  name: z
    .string(ZOD_ERROR)
    .nonempty("Заполните поле")
    .describe("Наименование команды"),
});

export type CreateTeamBodySchema = z.infer<typeof createTeamBodySchema>;
