/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { ZOD_ERROR } from "@/shared/constants/errors";

export const createEventBodySchema = z.object({
  title: z
    .string(ZOD_ERROR)
    .nonempty({ message: "Заполните поле" })
    .describe("Заголовок события"),
  start_timestamp: z.number(ZOD_ERROR).describe("Время начала события"),
  end_timestamp: z.number(ZOD_ERROR).describe("Время окончания события"),
});

export type CreateEventBodySchema = z.infer<typeof createEventBodySchema>;
