/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { ZOD_ERROR } from "@/shared/constants/errors";

export const createProjectColumnBodySchema = z.object({
  name: z
    .string(ZOD_ERROR)
    .nonempty("Заполните поле")
    .describe("Название столбца"),
  is_removable: z
    .boolean(ZOD_ERROR)
    .describe("Признак удаления столбца")
    .nullable()
    .nullish(),
  is_task_creation_allowed: z
    .boolean(ZOD_ERROR)
    .describe("Признак разрешения создания задач в столбце")
    .nullable()
    .nullish(),
  is_final_stage: z
    .boolean(ZOD_ERROR)
    .describe("Признак столбца финального этапа")
    .nullable()
    .nullish(),
});

export type CreateProjectColumnBodySchema = z.infer<
  typeof createProjectColumnBodySchema
>;
