/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createEventBodySchema } from "./createEventBodySchema";
import { z } from "zod";

export const createEventsBodySchema = z.object({
  events: z
    .array(z.lazy(() => createEventBodySchema))
    .describe("Список событий"),
});

export type CreateEventsBodySchema = z.infer<typeof createEventsBodySchema>;
