/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { goalBodyTaskSchema } from "./goalBodyTaskSchema";
import { z } from "zod";
import { ZOD_ERROR } from "@/shared/constants/errors";

export const createGoalBodySchema = z.object({
  title: z
    .string(ZOD_ERROR)
    .nonempty({ message: "Заполните поле" })
    .describe("Заголовок цели"),
  category: z
    .string(ZOD_ERROR)
    .nonempty({ message: "Заполните поле" })
    .describe("Категория цели"),
  deadline_date: z
    .string(ZOD_ERROR)
    .describe("Дата окончания цели")
    .nullable()
    .nullish(),
  note: z.string(ZOD_ERROR).describe("Примечание к цели").nullable().nullish(),
  tasks: z
    .array(z.lazy(() => goalBodyTaskSchema))
    .describe("Задачи цели")
    .nullable()
    .nullish(),
});

export type CreateGoalBodySchema = z.infer<typeof createGoalBodySchema>;
