/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const eventDtoSchema = z.object({
  id: z.number().describe('ID события'),
  title: z.string().describe('Заголовок события'),
  start_timestamp: z.number().describe('Время начала события'),
  end_timestamp: z.number().describe('Время окончания события'),
})

export type EventDtoSchema = z.infer<typeof eventDtoSchema>