/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { taskDtoSchema } from "./taskDtoSchema";
import { z } from "zod";

export const goalDtoSchema = z.object({
  id: z.number().describe("ID цели"),
  title: z.string().describe("Заголовок цели"),
  category: z.string().describe("Категория цели"),
  status: z.string().describe("Статус цели"),
  deadline_date: z
    .string()
    .describe("Дата окончания цели")
    .nullable()
    .nullish(),
  note: z.string().describe("Примечание к цели").nullable().nullish(),
  achieved_date: z
    .string()
    .describe("Дата выполнения цели")
    .nullable()
    .nullish(),
  tasks: z
    .array(z.lazy(() => taskDtoSchema))
    .describe("Задачи цели")
    .nullable()
    .nullish(),
});

export type GoalDtoSchema = z.infer<typeof goalDtoSchema>;
