/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { ZOD_ERROR } from "@/shared/constants/errors";

export const goalBodyTaskSchema = z.object({
  id: z.number(ZOD_ERROR).describe("ID задачи").optional(),
  title: z
    .string(ZOD_ERROR)
    .nonempty({ message: "Заполните поле" })
    .describe("Заголовок задачи"),
  deadline_date: z
    .string(ZOD_ERROR)
    .describe("Дата окончания задачи")
    .nullable()
    .nullish(),
  note: z.string(ZOD_ERROR).describe("Примечание задачи").nullable().nullish(),
  done_date: z
    .string(ZOD_ERROR)
    .describe("Дата выполнения задачи")
    .nullable()
    .nullish(),
});

export type GoalBodyTaskSchema = z.infer<typeof goalBodyTaskSchema>;
