/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const goalWithoutTasksDtoSchema = z.object({
  id: z.number().describe('ID цели'),
  title: z.string().describe('Заголовок цели'),
  category: z.string().describe('Категория цели'),
  status: z.string().describe('Статус цели'),
  deadline_date: z.string().describe('Дата окончания цели').nullable().nullish(),
  note: z.string().describe('Примечание к цели').nullable().nullish(),
  achieved_date: z.string().describe('Дата выполнения цели').nullable().nullish(),
})

export type GoalWithoutTasksDtoSchema = z.infer<typeof goalWithoutTasksDtoSchema>