/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod";
import { ZOD_ERROR } from "@/shared/constants/errors";

export const projectColumnSchema = z.object({
  id: z
    .string(ZOD_ERROR)
    .nonempty("Заполните поле")
    .describe("ID столбца проекта"),
  name: z
    .string(ZOD_ERROR)
    .nonempty("Заполните поле")
    .describe("Название столбца"),
  order: z
    .number(ZOD_ERROR)
    .min(0, { message: "Значение должно быть больше 0" })
    .describe("Порядковый номер столбца"),
  is_removable: z
    .boolean(ZOD_ERROR)
    .describe("Признак удаления столбца")
    .nullable()
    .nullish(),
  is_task_creation_allowed: z
    .boolean(ZOD_ERROR)
    .describe("Признак разрешения создания задач в столбце")
    .nullable()
    .nullish(),
  is_final_stage: z
    .boolean(ZOD_ERROR)
    .describe("Признак столбца финального этапа")
    .nullable()
    .nullish(),
});

export type ProjectColumnSchema = z.infer<typeof projectColumnSchema>;
