/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const teamGeneralInfoDtoSchema = z.object({
  id: z.number().describe('ID команды'),
  name: z.string().describe('Наименование команды'),
  members_length: z.number().describe('Количество участников команды'),
})

export type TeamGeneralInfoDtoSchema = z.infer<typeof teamGeneralInfoDtoSchema>