/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { projectColumnSchema } from "./projectColumnSchema";
import { z } from "zod";

export const updateProjectBodySchema = z.object({
  name: z.string().describe("Название проекта").nullable().nullish(),
  columns: z
    .array(z.lazy(() => projectColumnSchema))
    .describe("Описание проекта")
    .nullable()
    .nullish(),
});

export type UpdateProjectBodySchema = z.infer<typeof updateProjectBodySchema>;
