/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const updateResultSchema = z.object({})

export type UpdateResultSchema = z.infer<typeof updateResultSchema>