/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const updateProjectTaskListOrderBodySchema = z.object({
  id: z.number().describe('ID задачи'),
  list_order: z.number().describe('Порядок задачи в списке'),
})

export type UpdateProjectTaskListOrderBodySchema = z.infer<typeof updateProjectTaskListOrderBodySchema>