/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const updateTaskBodySchema = z.object({
  id: z.number().describe('ID задачи'),
  title: z.string().describe('Заголовок задачи'),
  deadline_date: z.string().describe('Дата окончания задачи').nullable().nullish(),
  done_date: z.string().describe('Дата выполнения задачи').nullable().nullish(),
  note: z.string().describe('Примечание задачи').nullable().nullish(),
})

export type UpdateTaskBodySchema = z.infer<typeof updateTaskBodySchema>