import {
  BicepsFlexed,
  BriefcaseBusiness,
  Church,
  Drum,
  GraduationCap,
  HandHeart,
  Handshake,
  HeartHandshake,
  HeartPulse,
  Image,
  Palette,
  Plane,
  SmilePlus,
  Trees,
  TrendingUp,
  Wallet,
} from "lucide-react";

const GOALS_CATEGORIES = {
  education: "education",
  career: "career",
  finance: "finance",
  health: "health",
  sports: "sports",
  relationships: "relationships",
  travel: "travel",
  creativity: "creativity",
  business: "business",
  personalGrowth: "personalGrowth",
  charity: "charity",
  hobby: "hobby",
  spirituality: "spirituality",
  ecology: "ecology",
  socialActivity: "socialActivity",
};

const GOAL_CATEGORIES_LABELS = {
  [GOALS_CATEGORIES.education]: "Образование",
  [GOALS_CATEGORIES.career]: "Карьера",
  [GOALS_CATEGORIES.finance]: "Финансы",
  [GOALS_CATEGORIES.health]: "Здоровье",
  [GOALS_CATEGORIES.sports]: "Спорт",
  [GOALS_CATEGORIES.relationships]: "Отношения",
  [GOALS_CATEGORIES.travel]: "Путешествия",
  [GOALS_CATEGORIES.creativity]: "Креативность",
  [GOALS_CATEGORIES.business]: "Бизнес",
  [GOALS_CATEGORIES.personalGrowth]: "Рост личности",
  [GOALS_CATEGORIES.charity]: "Благотворительность",
  [GOALS_CATEGORIES.hobby]: "Хобби",
  [GOALS_CATEGORIES.spirituality]: "Духовность",
  [GOALS_CATEGORIES.ecology]: "Экология",
  [GOALS_CATEGORIES.socialActivity]: "Социальная активность",
};

const GOAL_CATEGORY_ICONS = {
  [GOALS_CATEGORIES.education]: GraduationCap,
  [GOALS_CATEGORIES.career]: BriefcaseBusiness,
  [GOALS_CATEGORIES.finance]: Wallet,
  [GOALS_CATEGORIES.health]: HeartPulse,
  [GOALS_CATEGORIES.sports]: BicepsFlexed,
  [GOALS_CATEGORIES.relationships]: HandHeart,
  [GOALS_CATEGORIES.travel]: Plane,
  [GOALS_CATEGORIES.creativity]: Palette,
  [GOALS_CATEGORIES.business]: Handshake,
  [GOALS_CATEGORIES.personalGrowth]: TrendingUp,
  [GOALS_CATEGORIES.charity]: HeartHandshake,
  [GOALS_CATEGORIES.hobby]: Drum,
  [GOALS_CATEGORIES.spirituality]: Church,
  [GOALS_CATEGORIES.ecology]: Trees,
  [GOALS_CATEGORIES.socialActivity]: SmilePlus,
  default: Image,
};

export { GOALS_CATEGORIES, GOAL_CATEGORIES_LABELS, GOAL_CATEGORY_ICONS };
