const PROJECT_TASK_PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
} as const;

const PROJECT_TASK_PRIORITY_LABELS = {
  [PROJECT_TASK_PRIORITY.LOW]: "Низкий",
  [PROJECT_TASK_PRIORITY.MEDIUM]: "Средний",
  [PROJECT_TASK_PRIORITY.HIGH]: "Высокий",
  [PROJECT_TASK_PRIORITY.CRITICAL]: "Критический",
} as const;

export { PROJECT_TASK_PRIORITY, PROJECT_TASK_PRIORITY_LABELS };
