/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { BudgetAccountingCreateBodySchema } from "../BudgetAccountingCreateBodySchema";
import type { BudgetAccountingSchema } from "../BudgetAccountingSchema";

export type CreateBudgetAccounting200 = BudgetAccountingSchema;

export type CreateBudgetAccounting404 = BadRequest;

export type CreateBudgetAccountingMutationRequest =
  BudgetAccountingCreateBodySchema;

export type CreateBudgetAccountingMutationResponse = CreateBudgetAccounting200;

export type CreateBudgetAccountingMutation = {
  Response: CreateBudgetAccounting200;
  Request: CreateBudgetAccountingMutationRequest;
  Errors: CreateBudgetAccounting404;
};
