/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { CreateGoalBody } from "../CreateGoalBody";
import type { GoalDto } from "../GoalDto";

export type CreateGoal200 = GoalDto;

export type CreateGoal400 = BadRequest;

export type CreateGoalMutationRequest = CreateGoalBody;

export type CreateGoalMutationResponse = CreateGoal200;

export type CreateGoalMutation = {
  Response: CreateGoal200;
  Request: CreateGoalMutationRequest;
  Errors: CreateGoal400;
};
