/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";

export type DeleteBudgetAccountingPathParams = {
  /**
   * @type number
   */
  id: number;
};

export type DeleteBudgetAccounting200 = unknown;

export type DeleteBudgetAccounting404 = BadRequest;

export type DeleteBudgetAccountingMutationResponse = DeleteBudgetAccounting200;

export type DeleteBudgetAccountingMutation = {
  Response: DeleteBudgetAccounting200;
  PathParams: DeleteBudgetAccountingPathParams;
  Errors: DeleteBudgetAccounting404;
};
