/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";

export type GenerateGoals200 = unknown;

export type GenerateGoals400 = BadRequest;

export type GenerateGoalsMutationRequest = string;

export type GenerateGoalsMutationResponse = GenerateGoals200;

export type GenerateGoalsMutation = {
  Response: GenerateGoals200;
  Request: GenerateGoalsMutationRequest;
  Errors: GenerateGoals400;
};
