/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { BudgetAccountingResponseSchema } from "../BudgetAccountingResponseSchema";

export type GetBudgetAccountingQueryParams = {
  /**
   * @type string
   */
  year: string;
  /**
   * @type string
   */
  month: string;
};

export type GetBudgetAccounting200 = BudgetAccountingResponseSchema;

export type GetBudgetAccounting404 = BadRequest;

export type GetBudgetAccountingQueryResponse = GetBudgetAccounting200;

export type GetBudgetAccountingQuery = {
  Response: GetBudgetAccounting200;
  QueryParams: GetBudgetAccountingQueryParams;
  Errors: GetBudgetAccounting404;
};
