/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { GoalDto } from '../GoalDto.ts'

export type GetGoalsGeneralInfo200 = GoalDto[]

export type GetGoalsGeneralInfo400 = BadRequest

export type GetGoalsGeneralInfoQueryResponse = GetGoalsGeneralInfo200

export type GetGoalsGeneralInfoQuery = {
  Response: GetGoalsGeneralInfo200
  Errors: GetGoalsGeneralInfo400
}