/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { UpdateResult } from '../UpdateResult.ts'
import type { UpdateTaskBody } from '../UpdateTaskBody.ts'

export type UpdateTaskPathParams = {
  /**
   * @type string
   */
  task_id: string
}

export type UpdateTask200 = UpdateResult

export type UpdateTask400 = BadRequest

export type UpdateTaskMutationRequest = UpdateTaskBody

export type UpdateTaskMutationResponse = UpdateTask200

export type UpdateTaskMutation = {
  Response: UpdateTask200
  Request: UpdateTaskMutationRequest
  PathParams: UpdateTaskPathParams
  Errors: UpdateTask400
}