/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { UpdateResult } from "../UpdateResult";
import type { UpdateTaskBody } from "../UpdateTaskBody";

export type UpdateTasks200 = UpdateResult;

export type UpdateTasks400 = BadRequest;

export type UpdateTasksMutationRequest = UpdateTaskBody[];

export type UpdateTasksMutationResponse = UpdateTasks200;

export type UpdateTasksMutation = {
  Response: UpdateTasks200;
  Request: UpdateTasksMutationRequest;
  Errors: UpdateTasks400;
};
