/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { BudgetAccountingSchema } from "../BudgetAccountingSchema";

export type UpdateBudgetAccounting200 = BudgetAccountingSchema;

export type UpdateBudgetAccounting404 = BadRequest;

export type UpdateBudgetAccountingMutationRequest = BudgetAccountingSchema;

export type UpdateBudgetAccountingMutationResponse = UpdateBudgetAccounting200;

export type UpdateBudgetAccountingMutation = {
  Response: UpdateBudgetAccounting200;
  Request: UpdateBudgetAccountingMutationRequest;
  Errors: UpdateBudgetAccounting404;
};
