/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { UpdateGoalBody } from '../UpdateGoalBody.ts'
import type { UpdateResult } from '../UpdateResult.ts'

export type UpdateGoalPathParams = {
  /**
   * @type string
   */
  id: string
}

export type UpdateGoal200 = UpdateResult

export type UpdateGoal400 = BadRequest

export type UpdateGoalMutationRequest = UpdateGoalBody

export type UpdateGoalMutationResponse = UpdateGoal200

export type UpdateGoalMutation = {
  Response: UpdateGoal200
  Request: UpdateGoalMutationRequest
  PathParams: UpdateGoalPathParams
  Errors: UpdateGoal400
}