/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { UpdateResult } from "../UpdateResult";
import type { UpdateTaskListOrderBody } from "../UpdateTaskListOrderBody";

export type UpdateTaskListOrder200 = UpdateResult;

export type UpdateTaskListOrder400 = BadRequest;

export type UpdateTaskListOrderMutationRequest = UpdateTaskListOrderBody[];

export type UpdateTaskListOrderMutationResponse = UpdateTaskListOrder200;

export type UpdateTaskListOrderMutation = {
  Response: UpdateTaskListOrder200;
  Request: UpdateTaskListOrderMutationRequest;
  Errors: UpdateTaskListOrder400;
};
