/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { deleteTeamMembersBodySchema } from "../deleteTeamMembersBodySchema";
import { z } from "zod";

export const deleteTeamMembersPathParamsSchema = z.object({
  team_id: z.string(),
});

export type DeleteTeamMembersPathParamsSchema = z.infer<
  typeof deleteTeamMembersPathParamsSchema
>;

export const deleteTeamMembers200Schema = z.unknown();

export type DeleteTeamMembers200Schema = z.infer<
  typeof deleteTeamMembers200Schema
>;

export const deleteTeamMembers400Schema = z.lazy(() => badRequestSchema);

export type DeleteTeamMembers400Schema = z.infer<
  typeof deleteTeamMembers400Schema
>;

export const deleteTeamMembersMutationRequestSchema = z.lazy(
  () => deleteTeamMembersBodySchema,
);

export type DeleteTeamMembersMutationRequestSchema = z.infer<
  typeof deleteTeamMembersMutationRequestSchema
>;

export const deleteTeamMembersMutationResponseSchema = z.lazy(
  () => deleteTeamMembers200Schema,
);

export type DeleteTeamMembersMutationResponseSchema = z.infer<
  typeof deleteTeamMembersMutationResponseSchema
>;
