/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { z } from "zod";

export const joinTeamPathParamsSchema = z.object({
  id: z.string(),
});

export type JoinTeamPathParamsSchema = z.infer<typeof joinTeamPathParamsSchema>;

export const joinTeamQueryParamsSchema = z.object({
  jat: z.string(),
});

export type JoinTeamQueryParamsSchema = z.infer<
  typeof joinTeamQueryParamsSchema
>;

export const joinTeam200Schema = z.unknown();

export type JoinTeam200Schema = z.infer<typeof joinTeam200Schema>;

export const joinTeam400Schema = z.lazy(() => badRequestSchema);

export type JoinTeam400Schema = z.infer<typeof joinTeam400Schema>;

export const joinTeamMutationResponseSchema = z.lazy(() => joinTeam200Schema);

export type JoinTeamMutationResponseSchema = z.infer<
  typeof joinTeamMutationResponseSchema
>;
