/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { updateTeamMemberBodySchema } from "../updateTeamMemberBodySchema";
import { z } from "zod";

export const updateTeamMemberPathParamsSchema = z.object({
  member_id: z.string(),
  team_id: z.string(),
});

export type UpdateTeamMemberPathParamsSchema = z.infer<
  typeof updateTeamMemberPathParamsSchema
>;

export const updateTeamMember200Schema = z.unknown();

export type UpdateTeamMember200Schema = z.infer<
  typeof updateTeamMember200Schema
>;

export const updateTeamMember400Schema = z.lazy(() => badRequestSchema);

export type UpdateTeamMember400Schema = z.infer<
  typeof updateTeamMember400Schema
>;

export const updateTeamMemberMutationRequestSchema = z.lazy(
  () => updateTeamMemberBodySchema,
);

export type UpdateTeamMemberMutationRequestSchema = z.infer<
  typeof updateTeamMemberMutationRequestSchema
>;

export const updateTeamMemberMutationResponseSchema = z.lazy(
  () => updateTeamMember200Schema,
);

export type UpdateTeamMemberMutationResponseSchema = z.infer<
  typeof updateTeamMemberMutationResponseSchema
>;
