/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { CreateTeamBody } from "../CreateTeamBody";
import type { TeamDto } from "../TeamDto";

export type CreateTeam200 = TeamDto;

export type CreateTeam400 = BadRequest;

export type CreateTeamMutationRequest = CreateTeamBody;

export type CreateTeamMutationResponse = CreateTeam200;

export type CreateTeamMutation = {
  Response: CreateTeam200;
  Request: CreateTeamMutationRequest;
  Errors: CreateTeam400;
};
