/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'

export type DeleteTeamMemberPathParams = {
  /**
   * @type string
   */
  member_id: string
  /**
   * @type string
   */
  team_id: string
}

export type DeleteTeamMember200 = unknown

export type DeleteTeamMember400 = BadRequest

export type DeleteTeamMemberMutationResponse = DeleteTeamMember200

export type DeleteTeamMemberMutation = {
  Response: DeleteTeamMember200
  PathParams: DeleteTeamMemberPathParams
  Errors: DeleteTeamMember400
}