/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";

export type GetProjectsRightsPathParams = {
  /**
   * @type string
   */
  member_id: string;
  /**
   * @type string
   */
  team_id: string;
};

export type GetProjectsRights200 = string;

export type GetProjectsRights400 = BadRequest;

export type GetProjectsRightsQueryResponse = GetProjectsRights200;

export type GetProjectsRightsQuery = {
  Response: GetProjectsRights200;
  PathParams: GetProjectsRightsPathParams;
  Errors: GetProjectsRights400;
};
