/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { TeamDto } from "../TeamDto";

export type GetTeamPathParams = {
  /**
   * @type string
   */
  team_id: string;
};

export type GetTeam200 = TeamDto;

export type GetTeam400 = BadRequest;

export type GetTeamQueryResponse = GetTeam200;

export type GetTeamQuery = {
  Response: GetTeam200;
  PathParams: GetTeamPathParams;
  Errors: GetTeam400;
};
