/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { TeamDto } from '../TeamDto.ts'

export type GetTeamById200 = TeamDto

export type GetTeamById400 = BadRequest

export type GetTeamByIdQueryResponse = GetTeamById200

export type GetTeamByIdQuery = {
  Response: GetTeamById200
  Errors: GetTeamById400
}