/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { TeamDto } from "../TeamDto";

export type GetTeams200 = TeamDto[];

export type GetTeams400 = BadRequest;

export type GetTeamsQueryResponse = GetTeams200;

export type GetTeamsQuery = {
  Response: GetTeams200;
  Errors: GetTeams400;
};
