/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { InviteUserBody } from "../InviteUserBody";

export type InviteUser200 = unknown;

export type InviteUser400 = BadRequest;

export type InviteUserMutationRequest = InviteUserBody;

export type InviteUserMutationResponse = InviteUser200;

export type InviteUserMutation = {
  Response: InviteUser200;
  Request: InviteUserMutationRequest;
  Errors: InviteUser400;
};
