/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";

export type JoinTeamPathParams = {
  /**
   * @type string
   */
  id: string;
};

export type JoinTeamQueryParams = {
  /**
   * @type string
   */
  jat: string;
};

export type JoinTeam200 = unknown;

export type JoinTeam400 = BadRequest;

export type JoinTeamMutationResponse = JoinTeam200;

export type JoinTeamMutation = {
  Response: JoinTeam200;
  PathParams: JoinTeamPathParams;
  QueryParams: JoinTeamQueryParams;
  Errors: JoinTeam400;
};
