/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";

export type LeaveFromTeamPathParams = {
  /**
   * @type string
   */
  team_id: string;
};

export type LeaveFromTeam200 = unknown;

export type LeaveFromTeam400 = BadRequest;

export type LeaveFromTeamMutationResponse = LeaveFromTeam200;

export type LeaveFromTeamMutation = {
  Response: LeaveFromTeam200;
  PathParams: LeaveFromTeamPathParams;
  Errors: LeaveFromTeam400;
};
