/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { z } from "zod";

export const deleteTeamMemberPathParamsSchema = z.object({
  member_id: z.string(),
  team_id: z.string(),
});

export type DeleteTeamMemberPathParamsSchema = z.infer<
  typeof deleteTeamMemberPathParamsSchema
>;

export const deleteTeamMember200Schema = z.unknown();

export type DeleteTeamMember200Schema = z.infer<
  typeof deleteTeamMember200Schema
>;

export const deleteTeamMember400Schema = z.lazy(() => badRequestSchema);

export type DeleteTeamMember400Schema = z.infer<
  typeof deleteTeamMember400Schema
>;

export const deleteTeamMemberMutationResponseSchema = z.lazy(
  () => deleteTeamMember200Schema,
);

export type DeleteTeamMemberMutationResponseSchema = z.infer<
  typeof deleteTeamMemberMutationResponseSchema
>;
