/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { z } from "zod";

export const getProjectsRightsPathParamsSchema = z.object({
  member_id: z.string(),
  team_id: z.string(),
});

export type GetProjectsRightsPathParamsSchema = z.infer<
  typeof getProjectsRightsPathParamsSchema
>;

export const getProjectsRights200Schema = z.string();

export type GetProjectsRights200Schema = z.infer<
  typeof getProjectsRights200Schema
>;

export const getProjectsRights400Schema = z.lazy(() => badRequestSchema);

export type GetProjectsRights400Schema = z.infer<
  typeof getProjectsRights400Schema
>;

export const getProjectsRightsQueryResponseSchema = z.lazy(
  () => getProjectsRights200Schema,
);

export type GetProjectsRightsQueryResponseSchema = z.infer<
  typeof getProjectsRightsQueryResponseSchema
>;
