/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { z } from "zod";

export const getTeamJoinLinkPathParamsSchema = z.object({
  team_id: z.string(),
});

export type GetTeamJoinLinkPathParamsSchema = z.infer<
  typeof getTeamJoinLinkPathParamsSchema
>;

export const getTeamJoinLink200Schema = z.string();

export type GetTeamJoinLink200Schema = z.infer<typeof getTeamJoinLink200Schema>;

export const getTeamJoinLink400Schema = z.lazy(() => badRequestSchema);

export type GetTeamJoinLink400Schema = z.infer<typeof getTeamJoinLink400Schema>;

export const getTeamJoinLinkQueryResponseSchema = z.lazy(
  () => getTeamJoinLink200Schema,
);

export type GetTeamJoinLinkQueryResponseSchema = z.infer<
  typeof getTeamJoinLinkQueryResponseSchema
>;
