/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { teamDtoSchema } from "../teamDtoSchema";
import { z } from "zod";

export const getTeams200Schema = z.array(z.lazy(() => teamDtoSchema));

export type GetTeams200Schema = z.infer<typeof getTeams200Schema>;

export const getTeams400Schema = z.lazy(() => badRequestSchema);

export type GetTeams400Schema = z.infer<typeof getTeams400Schema>;

export const getTeamsQueryResponseSchema = z.lazy(() => getTeams200Schema);

export type GetTeamsQueryResponseSchema = z.infer<
  typeof getTeamsQueryResponseSchema
>;
