/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { teamGeneralInfoDtoSchema } from "../teamGeneralInfoDtoSchema";
import { z } from "zod";

export const getTeamGeneralInfoPathParamsSchema = z.object({
  team_id: z.string(),
});

export type GetTeamGeneralInfoPathParamsSchema = z.infer<
  typeof getTeamGeneralInfoPathParamsSchema
>;

export const getTeamGeneralInfo200Schema = z.lazy(
  () => teamGeneralInfoDtoSchema,
);

export type GetTeamGeneralInfo200Schema = z.infer<
  typeof getTeamGeneralInfo200Schema
>;

export const getTeamGeneralInfo400Schema = z.lazy(() => badRequestSchema);

export type GetTeamGeneralInfo400Schema = z.infer<
  typeof getTeamGeneralInfo400Schema
>;

export const getTeamGeneralInfoQueryResponseSchema = z.lazy(
  () => getTeamGeneralInfo200Schema,
);

export type GetTeamGeneralInfoQueryResponseSchema = z.infer<
  typeof getTeamGeneralInfoQueryResponseSchema
>;
