/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from '../badRequestSchema.ts'
import { inviteUserBodySchema } from '../inviteUserBodySchema.ts'
import { z } from 'zod'

export const inviteUser200Schema = z.unknown()

export type InviteUser200Schema = z.infer<typeof inviteUser200Schema>

export const inviteUser400Schema = z.lazy(() => badRequestSchema)

export type InviteUser400Schema = z.infer<typeof inviteUser400Schema>

export const inviteUserMutationRequestSchema = z.lazy(() => inviteUserBodySchema)

export type InviteUserMutationRequestSchema = z.infer<typeof inviteUserMutationRequestSchema>

export const inviteUserMutationResponseSchema = z.lazy(() => inviteUser200Schema)

export type InviteUserMutationResponseSchema = z.infer<typeof inviteUserMutationResponseSchema>