/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CheckAuth200 = unknown

export type CheckAuth401 = unknown

export type CheckAuthQueryResponse = CheckAuth200

export type CheckAuthQuery = {
  Response: CheckAuth200
  Errors: CheckAuth401
}