/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Logout200 = unknown

export type Logout400 = unknown

export type LogoutMutationResponse = Logout200

export type LogoutMutation = {
  Response: Logout200
  Errors: Logout400
}