/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createProjectColumnBodySchema = z.object({
  name: z.string().describe('Название столбца'),
  is_removable: z.boolean().describe('Признак удаления столбца').nullable().nullish(),
  is_task_creation_allowed: z.boolean().describe('Признак разрешения создания задач в столбце').nullable().nullish(),
  is_final_stage: z.boolean().describe('Признак столбца финального этапа').nullable().nullish(),
})

export type CreateProjectColumnBodySchema = z.infer<typeof createProjectColumnBodySchema>