/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createEventBodySchema = z.object({
  title: z.string().describe('Заголовок события'),
  start_timestamp: z.number().describe('Время начала события'),
  end_timestamp: z.number().describe('Время окончания события'),
})

export type CreateEventBodySchema = z.infer<typeof createEventBodySchema>