/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createNotificationBodySchema = z.object({
  title: z.string().describe('Заголовок уведомления'),
  description: z.string().describe('Описание уведомления').optional(),
  accept: z.string().describe('Ссылка на принятие уведомления').optional(),
  reject: z.string().describe('Ссылка на отклонение уведомления').optional(),
})

export type CreateNotificationBodySchema = z.infer<typeof createNotificationBodySchema>