/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createProjectBodySchema = z.object({
  name: z.string().min(1).describe('Название проекта'),
})

export type CreateProjectBodySchema = z.infer<typeof createProjectBodySchema>