/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createTeamBodySchema = z.object({
  name: z.string().describe('Наименование команды'),
})

export type CreateTeamBodySchema = z.infer<typeof createTeamBodySchema>