/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { projectColumnSchema } from "./projectColumnSchema";
import { z } from "zod";

export const createProjectTaskBodySchema = z.object({
  name: z.string().min(1).describe("Наименование задачи"),
  description: z.string().describe("Описание задачи").nullable().nullish(),
  column: z.lazy(() => projectColumnSchema).describe("Столбец задачи"),
  priority: z.string().describe("Приоритет задачи").nullable().nullish(),
  executor_member_id: z
    .number()
    .describe("ID исполнителя задачи")
    .nullable()
    .nullish(),
});

export type CreateProjectTaskBodySchema = z.infer<
  typeof createProjectTaskBodySchema
>;
