/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const deleteTeamMembersBodySchema = z.object({
  member_ids: z.array(z.number()).describe('ID участников команды'),
})

export type DeleteTeamMembersBodySchema = z.infer<typeof deleteTeamMembersBodySchema>