/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const eventEntitySchema = z.object({})

export type EventEntitySchema = z.infer<typeof eventEntitySchema>