/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { projectDtoSchema } from "./projectDtoSchema";
import { z } from "zod";

export const generalInfoProjectDtoSchema = z.object({
  upcoming_deadline: z.array(z.lazy(() => projectDtoSchema)),
  assigned_me: z.array(z.lazy(() => projectDtoSchema)),
});

export type GeneralInfoProjectDtoSchema = z.infer<
  typeof generalInfoProjectDtoSchema
>;
