/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const goalBodyTaskSchema = z.object({
  id: z.number().describe('ID задачи').optional(),
  title: z.string().min(1).describe('Заголовок задачи'),
  deadline_date: z.string().describe('Дата окончания задачи').nullable().nullish(),
  note: z.string().describe('Примечание задачи').nullable().nullish(),
  done_date: z.string().describe('Дата выполнения задачи').nullable().nullish(),
})

export type GoalBodyTaskSchema = z.infer<typeof goalBodyTaskSchema>