/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const goalEntitySchema = z.object({})

export type GoalEntitySchema = z.infer<typeof goalEntitySchema>