/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const inviteUserBodySchema = z.object({
  user_invite_id: z.string().describe('ID приглашения пользователя'),
  team_id: z.number().describe('ID команды'),
})

export type InviteUserBodySchema = z.infer<typeof inviteUserBodySchema>