/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userDtoSchema } from "./userDtoSchema";
import { z } from "zod";

export const memberDtoSchema = z.object({
  user: z.lazy(() => userDtoSchema).describe("Данные пользователя"),
  role: z.string().describe("Роль в команде"),
});

export type MemberDtoSchema = z.infer<typeof memberDtoSchema>;
