/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const notificationEntitySchema = z.object({})

export type NotificationEntitySchema = z.infer<typeof notificationEntitySchema>