/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const projectColumnSchema = z.object({
  id: z.string().describe('ID столбца проекта'),
  name: z.string().describe('Название столбца'),
  order: z.number().describe('Порядковый номер столбца'),
  removable: z.boolean().describe('Признак удаления столбца').nullable().nullish(),
})

export type ProjectColumnSchema = z.infer<typeof projectColumnSchema>