/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { memberDtoSchema } from "./memberDtoSchema";
import { projectColumnSchema } from "./projectColumnSchema";
import { z } from "zod";

export const projectTaskDtoSchema = z.object({
  id: z.number().describe("ID задачи"),
  name: z.string().describe("Наименование задачи"),
  description: z.string().describe("Описание задачи").nullable().nullish(),
  column: z.lazy(() => projectColumnSchema).describe("Столбец задачи"),
  priority: z.string().describe("Приоритет задачи").nullable().nullish(),
  author: z.lazy(() => memberDtoSchema).describe("Автор задачи"),
  executor: z
    .lazy(() => memberDtoSchema)
    .describe("Исполнитель задачи")
    .nullable()
    .nullish(),
});

export type ProjectTaskDtoSchema = z.infer<typeof projectTaskDtoSchema>;
