/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const projectRightsDtoSchema = z.object({
  project_id: z.number().describe('ID проекта'),
  create: z.boolean().describe('Создание'),
  read: z.boolean().describe('Чтение'),
  update: z.boolean().describe('Обновление'),
  delete: z.boolean().describe('Удаление'),
})

export type ProjectRightsDtoSchema = z.infer<typeof projectRightsDtoSchema>