/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const projectEntitySchema = z.object({})

export type ProjectEntitySchema = z.infer<typeof projectEntitySchema>