/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { teamDtoSchema } from "./teamDtoSchema";
import { z } from "zod";

export const projectDtoSchema = z.object({
  id: z.number().describe("ID проекта"),
  name: z.string().describe("Название проекта"),
  team: z.lazy(() => teamDtoSchema).describe("Команда проекта"),
});

export type ProjectDtoSchema = z.infer<typeof projectDtoSchema>;
