/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const taskDtoSchema = z.object({
  id: z.number().describe('ID задачи'),
  title: z.string().describe('Заголовок задачи'),
  deadline_date: z.string().describe('Дата окончания задачи'),
  note: z.string().describe('Примечание задачи'),
  done_date: z.string().describe('Дата выполнения задачи'),
})

export type TaskDtoSchema = z.infer<typeof taskDtoSchema>