/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const teamEntitySchema = z.object({})

export type TeamEntitySchema = z.infer<typeof teamEntitySchema>