/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { memberDtoSchema } from "./memberDtoSchema";
import { z } from "zod";

export const teamDtoSchema = z.object({
  id: z.number().describe("ID команды"),
  name: z.string().describe("Наименование команды"),
  user_role: z.string().describe("Роль пользователя в команде"),
  members: z.array(z.lazy(() => memberDtoSchema)).describe("Участники команды"),
});

export type TeamDtoSchema = z.infer<typeof teamDtoSchema>;
