/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const updateGoalListOrderBodySchema = z.object({
  id: z.number().describe('ID цели'),
  list_order: z.number().describe('Порядок цели в списке'),
})

export type UpdateGoalListOrderBodySchema = z.infer<typeof updateGoalListOrderBodySchema>