/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { goalBodyTaskSchema } from "./goalBodyTaskSchema";
import { z } from "zod";

export const updateGoalBodySchema = z.object({
  title: z.string().describe("Заголовок цели").optional(),
  category: z.string().describe("Категория цели").optional(),
  status: z.string().describe("Статус цели").optional(),
  deadline_date: z
    .string()
    .describe("Дата окончания цели")
    .nullable()
    .nullish(),
  note: z.string().describe("Примечание к цели").nullable().nullish(),
  achieved_date: z
    .string()
    .describe("Дата выполнения цели")
    .nullable()
    .nullish(),
  tasks: z
    .array(z.lazy(() => goalBodyTaskSchema))
    .describe("Задачи цели")
    .nullable()
    .nullish(),
});

export type UpdateGoalBodySchema = z.infer<typeof updateGoalBodySchema>;
