/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { projectRightsDtoSchema } from "./projectRightsDtoSchema";
import { z } from "zod";

export const updateTeamMemberBodySchema = z.object({
  role: z.string().min(1).describe("Роль участника команды"),
  projects_rights: z
    .array(z.lazy(() => projectRightsDtoSchema))
    .describe("Массив прав в проектах")
    .optional(),
});

export type UpdateTeamMemberBodySchema = z.infer<
  typeof updateTeamMemberBodySchema
>;
