/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { projectColumnSchema } from "./projectColumnSchema";
import { z } from "zod";

export const updateProjectTaskBodySchema = z.object({
  name: z.string().describe("Наименование задачи").nullable().nullish(),
  description: z.string().describe("Описание задачи").nullable().nullish(),
  column: z
    .lazy(() => projectColumnSchema)
    .describe("Столбец задачи")
    .nullable()
    .nullish(),
  priority: z.string().describe("Приоритет задачи").nullable().nullish(),
  executor_member_id: z
    .number()
    .describe("ID исполнителя задачи")
    .nullable()
    .nullish(),
});

export type UpdateProjectTaskBodySchema = z.infer<
  typeof updateProjectTaskBodySchema
>;
