/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const userDtoSchema = z.object({
  id: z.number().describe('ID пользователя'),
  username: z.string().describe('Имя пользователя'),
  email: z.string().describe('Email пользователя'),
  picture_url: z.string().describe('Изображение пользователя'),
})

export type UserDtoSchema = z.infer<typeof userDtoSchema>