/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from "@/shared/api/axios-client";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/axios-client";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type {
  CreateGoalMutationRequest,
  CreateGoalMutationResponse,
  CreateGoal400,
} from "../../models/goals/CreateGoal";
import { useMutation } from "@tanstack/react-query";

export const createGoalMutationKey = () => [{ url: "/goals" }] as const;

export type CreateGoalMutationKey = ReturnType<typeof createGoalMutationKey>;

/**
 * @summary Create goal
 * {@link /goals}
 */
export async function createGoal(
  { data }: { data: CreateGoalMutationRequest },
  config: Partial<RequestConfig<CreateGoalMutationRequest>> & {
    client?: typeof client;
  } = {},
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    CreateGoalMutationResponse,
    ResponseErrorConfig<CreateGoal400>,
    CreateGoalMutationRequest
  >({
    method: "POST",
    url: `/goals`,
    data,
    ...requestConfig,
  });
  return res.data;
}

/**
 * @summary Create goal
 * {@link /goals}
 */
export function useCreateGoal<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateGoalMutationResponse,
      ResponseErrorConfig<CreateGoal400>,
      { data: CreateGoalMutationRequest },
      TContext
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig<CreateGoalMutationRequest>> & {
      client?: typeof client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createGoalMutationKey();

  return useMutation<
    CreateGoalMutationResponse,
    ResponseErrorConfig<CreateGoal400>,
    { data: CreateGoalMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return createGoal({ data }, config);
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  );
}
