/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from "@/shared/api/axios-client";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/axios-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetBudgetAccountingQueryResponse,
  GetBudgetAccountingQueryParams,
  GetBudgetAccounting404,
} from "../../models/goals/GetBudgetAccounting";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getBudgetAccountingQueryKey = (
  params: GetBudgetAccountingQueryParams,
) => [{ url: "/budget/accounting" }, ...(params ? [params] : [])] as const;

export type GetBudgetAccountingQueryKey = ReturnType<
  typeof getBudgetAccountingQueryKey
>;

/**
 * {@link /budget/accounting}
 */
export async function getBudgetAccounting(
  { params }: { params: GetBudgetAccountingQueryParams },
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    GetBudgetAccountingQueryResponse,
    ResponseErrorConfig<GetBudgetAccounting404>,
    unknown
  >({
    method: "GET",
    url: `/budget/accounting`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getBudgetAccountingQueryOptions(
  { params }: { params: GetBudgetAccountingQueryParams },
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getBudgetAccountingQueryKey(params);
  return queryOptions<
    GetBudgetAccountingQueryResponse,
    ResponseErrorConfig<GetBudgetAccounting404>,
    GetBudgetAccountingQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getBudgetAccounting({ params }, config);
    },
  });
}

/**
 * {@link /budget/accounting}
 */
export function useGetBudgetAccounting<
  TData = GetBudgetAccountingQueryResponse,
  TQueryData = GetBudgetAccountingQueryResponse,
  TQueryKey extends QueryKey = GetBudgetAccountingQueryKey,
>(
  { params }: { params: GetBudgetAccountingQueryParams },
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetBudgetAccountingQueryResponse,
        ResponseErrorConfig<GetBudgetAccounting404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & {
      client?: QueryClient;
    };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {};
  const queryKey =
    queryOptions?.queryKey ?? getBudgetAccountingQueryKey(params);

  const query = useQuery(
    {
      ...(getBudgetAccountingQueryOptions(
        { params },
        config,
      ) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, "queryKey">),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetBudgetAccounting404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
