/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from "@/shared/api/axios-client";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/axios-client";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type {
  UpdateBudgetAccountingMutationRequest,
  UpdateBudgetAccountingMutationResponse,
  UpdateBudgetAccounting404,
} from "../../models/goals/UpdateBudgetAccounting";
import { useMutation } from "@tanstack/react-query";

export const updateBudgetAccountingMutationKey = () =>
  [{ url: "/budget/accounting/update" }] as const;

export type UpdateBudgetAccountingMutationKey = ReturnType<
  typeof updateBudgetAccountingMutationKey
>;

/**
 * {@link /budget/accounting/update}
 */
export async function updateBudgetAccounting(
  { data }: { data: UpdateBudgetAccountingMutationRequest },
  config: Partial<RequestConfig<UpdateBudgetAccountingMutationRequest>> & {
    client?: typeof client;
  } = {},
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    UpdateBudgetAccountingMutationResponse,
    ResponseErrorConfig<UpdateBudgetAccounting404>,
    UpdateBudgetAccountingMutationRequest
  >({
    method: "PUT",
    url: `/budget/accounting/update`,
    data,
    ...requestConfig,
  });
  return res.data;
}

/**
 * {@link /budget/accounting/update}
 */
export function useUpdateBudgetAccounting<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpdateBudgetAccountingMutationResponse,
      ResponseErrorConfig<UpdateBudgetAccounting404>,
      { data: UpdateBudgetAccountingMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpdateBudgetAccountingMutationRequest>> & {
      client?: typeof client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? updateBudgetAccountingMutationKey();

  return useMutation<
    UpdateBudgetAccountingMutationResponse,
    ResponseErrorConfig<UpdateBudgetAccounting404>,
    { data: UpdateBudgetAccountingMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return updateBudgetAccounting({ data }, config);
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  );
}
