/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { z } from "zod";

export const generateGoals200Schema = z.unknown();

export type GenerateGoals200Schema = z.infer<typeof generateGoals200Schema>;

export const generateGoals400Schema = z.lazy(() => badRequestSchema);

export type GenerateGoals400Schema = z.infer<typeof generateGoals400Schema>;

export const generateGoalsMutationRequestSchema = z.string();

export type GenerateGoalsMutationRequestSchema = z.infer<
  typeof generateGoalsMutationRequestSchema
>;

export const generateGoalsMutationResponseSchema = z.lazy(
  () => generateGoals200Schema,
);

export type GenerateGoalsMutationResponseSchema = z.infer<
  typeof generateGoalsMutationResponseSchema
>;
