/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { taskDtoSchema } from "../taskDtoSchema";
import { z } from "zod";

export const getTasks200Schema = z.array(z.lazy(() => taskDtoSchema));

export type GetTasks200Schema = z.infer<typeof getTasks200Schema>;

export const getTasks400Schema = z.lazy(() => badRequestSchema);

export type GetTasks400Schema = z.infer<typeof getTasks400Schema>;

export const getTasksQueryResponseSchema = z.lazy(() => getTasks200Schema);

export type GetTasksQueryResponseSchema = z.infer<
  typeof getTasksQueryResponseSchema
>;
