/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { updateResultSchema } from "../updateResultSchema";
import { updateTaskBodySchema } from "../updateTaskBodySchema";
import { z } from "zod";

export const updateTasks200Schema = z.lazy(() => updateResultSchema);

export type UpdateTasks200Schema = z.infer<typeof updateTasks200Schema>;

export const updateTasks400Schema = z.lazy(() => badRequestSchema);

export type UpdateTasks400Schema = z.infer<typeof updateTasks400Schema>;

export const updateTasksMutationRequestSchema = z.array(
  z.lazy(() => updateTaskBodySchema),
);

export type UpdateTasksMutationRequestSchema = z.infer<
  typeof updateTasksMutationRequestSchema
>;

export const updateTasksMutationResponseSchema = z.lazy(
  () => updateTasks200Schema,
);

export type UpdateTasksMutationResponseSchema = z.infer<
  typeof updateTasksMutationResponseSchema
>;
