/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from "@/shared/api/axios-client";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/axios-client";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type {
  CreateProjectParentTaskMutationRequest,
  CreateProjectParentTaskMutationResponse,
  CreateProjectParentTaskPathParams,
  CreateProjectParentTask400,
} from "../../models/projects/CreateProjectParentTask";
import { useMutation } from "@tanstack/react-query";

export const createProjectParentTaskMutationKey = () =>
  [{ url: "/projects/{project_id}/parent_tasks" }] as const;

export type CreateProjectParentTaskMutationKey = ReturnType<
  typeof createProjectParentTaskMutationKey
>;

/**
 * @summary Create project parent task
 * {@link /projects/:project_id/parent_tasks}
 */
export async function createProjectParentTask(
  {
    project_id,
    data,
  }: {
    project_id: CreateProjectParentTaskPathParams["project_id"];
    data: CreateProjectParentTaskMutationRequest;
  },
  config: Partial<RequestConfig<CreateProjectParentTaskMutationRequest>> & {
    client?: typeof client;
  } = {},
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    CreateProjectParentTaskMutationResponse,
    ResponseErrorConfig<CreateProjectParentTask400>,
    CreateProjectParentTaskMutationRequest
  >({
    method: "POST",
    url: `/projects/${project_id}/parent_tasks`,
    data,
    ...requestConfig,
  });
  return res.data;
}

/**
 * @summary Create project parent task
 * {@link /projects/:project_id/parent_tasks}
 */
export function useCreateProjectParentTask<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreateProjectParentTaskMutationResponse,
      ResponseErrorConfig<CreateProjectParentTask400>,
      {
        project_id: CreateProjectParentTaskPathParams["project_id"];
        data: CreateProjectParentTaskMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CreateProjectParentTaskMutationRequest>> & {
      client?: typeof client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? createProjectParentTaskMutationKey();

  return useMutation<
    CreateProjectParentTaskMutationResponse,
    ResponseErrorConfig<CreateProjectParentTask400>,
    {
      project_id: CreateProjectParentTaskPathParams["project_id"];
      data: CreateProjectParentTaskMutationRequest;
    },
    TContext
  >(
    {
      mutationFn: async ({ project_id, data }) => {
        return createProjectParentTask({ project_id, data }, config);
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  );
}
