/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from "@/shared/api/axios-client";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@/shared/api/axios-client";
import type { UseMutationOptions, QueryClient } from "@tanstack/react-query";
import type {
  DeleteProjectParentTaskMutationResponse,
  DeleteProjectParentTaskPathParams,
  DeleteProjectParentTask400,
} from "../../models/projects/DeleteProjectParentTask";
import { useMutation } from "@tanstack/react-query";

export const deleteProjectParentTaskMutationKey = () =>
  [{ url: "/projects/{project_id}/parent_tasks/{parent_task_id}" }] as const;

export type DeleteProjectParentTaskMutationKey = ReturnType<
  typeof deleteProjectParentTaskMutationKey
>;

/**
 * @summary Delete project parent task
 * {@link /projects/:project_id/parent_tasks/:parent_task_id}
 */
export async function deleteProjectParentTask(
  {
    parent_task_id,
    project_id,
  }: {
    parent_task_id: DeleteProjectParentTaskPathParams["parent_task_id"];
    project_id: DeleteProjectParentTaskPathParams["project_id"];
  },
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config;

  const res = await request<
    DeleteProjectParentTaskMutationResponse,
    ResponseErrorConfig<DeleteProjectParentTask400>,
    unknown
  >({
    method: "DELETE",
    url: `/projects/${project_id}/parent_tasks/${parent_task_id}`,
    ...requestConfig,
  });
  return res.data;
}

/**
 * @summary Delete project parent task
 * {@link /projects/:project_id/parent_tasks/:parent_task_id}
 */
export function useDeleteProjectParentTask<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteProjectParentTaskMutationResponse,
      ResponseErrorConfig<DeleteProjectParentTask400>,
      {
        parent_task_id: DeleteProjectParentTaskPathParams["parent_task_id"];
        project_id: DeleteProjectParentTaskPathParams["project_id"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteProjectParentTaskMutationKey();

  return useMutation<
    DeleteProjectParentTaskMutationResponse,
    ResponseErrorConfig<DeleteProjectParentTask400>,
    {
      parent_task_id: DeleteProjectParentTaskPathParams["parent_task_id"];
      project_id: DeleteProjectParentTaskPathParams["project_id"];
    },
    TContext
  >(
    {
      mutationFn: async ({ parent_task_id, project_id }) => {
        return deleteProjectParentTask({ parent_task_id, project_id }, config);
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  );
}
