/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { CreateNotificationBody } from "../CreateNotificationBody";
import type { NotificationDto } from "../NotificationDto";

export type CreateNotification200 = NotificationDto;

export type CreateNotification400 = BadRequest;

export type CreateNotificationMutationRequest = CreateNotificationBody;

export type CreateNotificationMutationResponse = CreateNotification200;

export type CreateNotificationMutation = {
  Response: CreateNotification200;
  Request: CreateNotificationMutationRequest;
  Errors: CreateNotification400;
};
