/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { CreateNotificationBody } from '../CreateNotificationBody.ts'
import type { NotificationDto } from '../NotificationDto.ts'

export type CreateNotification200 = NotificationDto

export type CreateNotification400 = BadRequest

export type CreateNotificationMutationRequest = CreateNotificationBody

export type CreateNotificationMutationResponse = CreateNotification200

export type CreateNotificationMutation = {
  Response: CreateNotification200
  Request: CreateNotificationMutationRequest
  Errors: CreateNotification400
}