/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { CreateProjectBody } from "../CreateProjectBody";
import type { ProjectDto } from "../ProjectDto";

export type CreateProjectPathParams = {
  /**
   * @type number
   */
  team_id: number;
};

export type CreateProject200 = ProjectDto;

export type CreateProject400 = BadRequest;

export type CreateProjectMutationRequest = CreateProjectBody;

export type CreateProjectMutationResponse = CreateProject200;

export type CreateProjectMutation = {
  Response: CreateProject200;
  Request: CreateProjectMutationRequest;
  PathParams: CreateProjectPathParams;
  Errors: CreateProject400;
};
