/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { CreateProjectParentTaskBody } from "../CreateProjectParentTaskBody";
import type { ProjectParentTaskDto } from "../ProjectParentTaskDto";

export type CreateProjectParentTaskPathParams = {
  /**
   * @type number
   */
  project_id: number;
};

export type CreateProjectParentTask200 = ProjectParentTaskDto;

export type CreateProjectParentTask400 = BadRequest;

export type CreateProjectParentTaskMutationRequest =
  CreateProjectParentTaskBody;

export type CreateProjectParentTaskMutationResponse =
  CreateProjectParentTask200;

export type CreateProjectParentTaskMutation = {
  Response: CreateProjectParentTask200;
  Request: CreateProjectParentTaskMutationRequest;
  PathParams: CreateProjectParentTaskPathParams;
  Errors: CreateProjectParentTask400;
};
