/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { CreateProjectTaskBody } from "../CreateProjectTaskBody";
import type { ProjectTaskDto } from "../ProjectTaskDto";

export type CreateProjectTaskPathParams = {
  /**
   * @type number
   */
  project_id: number;
};

export type CreateProjectTask200 = ProjectTaskDto;

export type CreateProjectTask400 = BadRequest;

export type CreateProjectTaskMutationRequest = CreateProjectTaskBody;

export type CreateProjectTaskMutationResponse = CreateProjectTask200;

export type CreateProjectTaskMutation = {
  Response: CreateProjectTask200;
  Request: CreateProjectTaskMutationRequest;
  PathParams: CreateProjectTaskPathParams;
  Errors: CreateProjectTask400;
};
