/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { ProjectParentTaskDto } from "../ProjectParentTaskDto";

export type DeleteProjectParentTaskPathParams = {
  /**
   * @type number
   */
  parent_task_id: number;
  /**
   * @type string
   */
  project_id: string;
};

export type DeleteProjectParentTask200 = ProjectParentTaskDto;

export type DeleteProjectParentTask400 = BadRequest;

export type DeleteProjectParentTaskMutationResponse =
  DeleteProjectParentTask200;

export type DeleteProjectParentTaskMutation = {
  Response: DeleteProjectParentTask200;
  PathParams: DeleteProjectParentTaskPathParams;
  Errors: DeleteProjectParentTask400;
};
