/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { ShortInfoProjectDto } from '../ShortInfoProjectDto.ts'

export type GetProjectsQueryParams = {
  /**
   * @type string
   */
  team_id: string
}

export type GetProjects200 = ShortInfoProjectDto[]

export type GetProjects400 = BadRequest

export type GetProjectsQueryResponse = GetProjects200

export type GetProjectsQuery = {
  Response: GetProjects200
  QueryParams: GetProjectsQueryParams
  Errors: GetProjects400
}