/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { ProjectDto } from "../ProjectDto";

export type GetProjectsQueryParams = {
  /**
   * @type string
   */
  team_id: string;
};

export type GetProjects200 = ProjectDto[];

export type GetProjects400 = BadRequest;

export type GetProjectsQueryResponse = GetProjects200;

export type GetProjectsQuery = {
  Response: GetProjects200;
  QueryParams: GetProjectsQueryParams;
  Errors: GetProjects400;
};
