/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { ProjectTaskDto } from '../ProjectTaskDto.ts'
import type { UpdateProjectTaskBody } from '../UpdateProjectTaskBody.ts'

export type UpdateProjectTaskPathParams = {
  /**
   * @type number
   */
  task_id: number
  /**
   * @type number
   */
  project_id: number
}

export type UpdateProjectTask200 = ProjectTaskDto

export type UpdateProjectTask400 = BadRequest

export type UpdateProjectTaskMutationRequest = UpdateProjectTaskBody

export type UpdateProjectTaskMutationResponse = UpdateProjectTask200

export type UpdateProjectTaskMutation = {
  Response: UpdateProjectTask200
  Request: UpdateProjectTaskMutationRequest
  PathParams: UpdateProjectTaskPathParams
  Errors: UpdateProjectTask400
}