/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { UpdateProjectTaskListOrderBody } from '../UpdateProjectTaskListOrderBody.ts'
import type { UpdateResult } from '../UpdateResult.ts'

export type UpdateProjectTaskListOrderPathParams = {
  /**
   * @type number
   */
  project_id: number
}

export type UpdateProjectTaskListOrder200 = UpdateResult

export type UpdateProjectTaskListOrder400 = BadRequest

export type UpdateProjectTaskListOrderMutationRequest = UpdateProjectTaskListOrderBody[]

export type UpdateProjectTaskListOrderMutationResponse = UpdateProjectTaskListOrder200

export type UpdateProjectTaskListOrderMutation = {
  Response: UpdateProjectTaskListOrder200
  Request: UpdateProjectTaskListOrderMutationRequest
  PathParams: UpdateProjectTaskListOrderPathParams
  Errors: UpdateProjectTaskListOrder400
}