/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { ProjectDto } from '../ProjectDto.ts'
import type { UpdateProjectBody } from '../UpdateProjectBody.ts'

export type UpdateProjectPathParams = {
  /**
   * @type number
   */
  project_id: number
}

export type UpdateProject200 = ProjectDto

export type UpdateProject400 = BadRequest

export type UpdateProjectMutationRequest = UpdateProjectBody

export type UpdateProjectMutationResponse = UpdateProject200

export type UpdateProjectMutation = {
  Response: UpdateProject200
  Request: UpdateProjectMutationRequest
  PathParams: UpdateProjectPathParams
  Errors: UpdateProject400
}