/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { ProjectTaskDto } from "../ProjectTaskDto";
import type { UpdateProjectTaskListOrderBody } from "../UpdateProjectTaskListOrderBody";

export type UpdateProjectTaskListOrderPathParams = {
  /**
   * @type number
   */
  project_id: number;
};

export type UpdateProjectTaskListOrder200 = ProjectTaskDto[];

export type UpdateProjectTaskListOrder400 = BadRequest;

export type UpdateProjectTaskListOrderMutationRequest =
  UpdateProjectTaskListOrderBody[];

export type UpdateProjectTaskListOrderMutationResponse =
  UpdateProjectTaskListOrder200;

export type UpdateProjectTaskListOrderMutation = {
  Response: UpdateProjectTaskListOrder200;
  Request: UpdateProjectTaskListOrderMutationRequest;
  PathParams: UpdateProjectTaskListOrderPathParams;
  Errors: UpdateProjectTaskListOrder400;
};
