/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { ProjectColumn } from '../ProjectColumn.ts'
import type { ProjectDto } from '../ProjectDto.ts'

export type UpdateProjectColumnPathParams = {
  /**
   * @type string
   */
  column_id: string
  /**
   * @type number
   */
  project_id: number
}

export type UpdateProjectColumn200 = ProjectDto

export type UpdateProjectColumn400 = BadRequest

export type UpdateProjectColumnMutationRequest = ProjectColumn

export type UpdateProjectColumnMutationResponse = UpdateProjectColumn200

export type UpdateProjectColumnMutation = {
  Response: UpdateProjectColumn200
  Request: UpdateProjectColumnMutationRequest
  PathParams: UpdateProjectColumnPathParams
  Errors: UpdateProjectColumn400
}