/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { ProjectParentTaskDto } from "../ProjectParentTaskDto";
import type { UpdateProjectParentTaskBody } from "../UpdateProjectParentTaskBody";

export type UpdateProjectParentTaskPathParams = {
  /**
   * @type number
   */
  parent_task_id: number;
  /**
   * @type number
   */
  project_id: number;
};

export type UpdateProjectParentTask200 = ProjectParentTaskDto;

export type UpdateProjectParentTask400 = BadRequest;

export type UpdateProjectParentTaskMutationRequest =
  UpdateProjectParentTaskBody;

export type UpdateProjectParentTaskMutationResponse =
  UpdateProjectParentTask200;

export type UpdateProjectParentTaskMutation = {
  Response: UpdateProjectParentTask200;
  Request: UpdateProjectParentTaskMutationRequest;
  PathParams: UpdateProjectParentTaskPathParams;
  Errors: UpdateProjectParentTask400;
};
