/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { CreateEventsBody } from '../CreateEventsBody.ts'
import type { EventDto } from '../EventDto.ts'

export type CreateEvents200 = EventDto[]

export type CreateEvents400 = BadRequest

export type CreateEventsMutationRequest = CreateEventsBody

export type CreateEventsMutationResponse = CreateEvents200

export type CreateEventsMutation = {
  Response: CreateEvents200
  Request: CreateEventsMutationRequest
  Errors: CreateEvents400
}