/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { CreateEventsBody } from "../CreateEventsBody";
import type { EventDto } from "../EventDto";

export type CreateEvents200 = EventDto[];

export type CreateEvents400 = BadRequest;

export type CreateEventsMutationRequest = CreateEventsBody;

export type CreateEventsMutationResponse = CreateEvents200;

export type CreateEventsMutation = {
  Response: CreateEvents200;
  Request: CreateEventsMutationRequest;
  Errors: CreateEvents400;
};
