/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'

export type DeleteEvent200 = unknown

export type DeleteEvent400 = BadRequest

export type DeleteEventMutationResponse = DeleteEvent200

export type DeleteEventMutation = {
  Response: DeleteEvent200
  Errors: DeleteEvent400
}