/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from "../BadRequest";
import type { EventDto } from "../EventDto";

export type GetEventsQueryParams = {
  /**
   * @type string
   */
  end_period: string;
  /**
   * @type string
   */
  start_period: string;
};

export type GetEvents200 = EventDto[];

export type GetEvents400 = BadRequest;

export type GetEventsQueryResponse = GetEvents200;

export type GetEventsQuery = {
  Response: GetEvents200;
  QueryParams: GetEventsQueryParams;
  Errors: GetEvents400;
};
