/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequest } from '../BadRequest.ts'
import type { UpdateEventBody } from '../UpdateEventBody.ts'
import type { UpdateResult } from '../UpdateResult.ts'

export type UpdateEventPathParams = {
  /**
   * @type string
   */
  id: string
}

export type UpdateEvent200 = UpdateResult

export type UpdateEvent400 = BadRequest

export type UpdateEventMutationRequest = UpdateEventBody

export type UpdateEventMutationResponse = UpdateEvent200

export type UpdateEventMutation = {
  Response: UpdateEvent200
  Request: UpdateEventMutationRequest
  PathParams: UpdateEventPathParams
  Errors: UpdateEvent400
}