/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { profileDtoSchema } from "../profileDtoSchema";
import { z } from "zod";

export const getProfile200Schema = z.lazy(() => profileDtoSchema);

export type GetProfile200Schema = z.infer<typeof getProfile200Schema>;

export const getProfile404Schema = z.lazy(() => badRequestSchema);

export type GetProfile404Schema = z.infer<typeof getProfile404Schema>;

export const getProfileQueryResponseSchema = z.lazy(() => getProfile200Schema);

export type GetProfileQueryResponseSchema = z.infer<
  typeof getProfileQueryResponseSchema
>;
