/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const logout200Schema = z.unknown()

export type Logout200Schema = z.infer<typeof logout200Schema>

export const logout400Schema = z.unknown()

export type Logout400Schema = z.infer<typeof logout400Schema>

export const logoutMutationResponseSchema = z.lazy(() => logout200Schema)

export type LogoutMutationResponseSchema = z.infer<typeof logoutMutationResponseSchema>