/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { goalDtoSchema } from "../goalDtoSchema";
import { z } from "zod";

export const getGoalsGeneralInfo200Schema = z.array(
  z.lazy(() => goalDtoSchema),
);

export type GetGoalsGeneralInfo200Schema = z.infer<
  typeof getGoalsGeneralInfo200Schema
>;

export const getGoalsGeneralInfo400Schema = z.lazy(() => badRequestSchema);

export type GetGoalsGeneralInfo400Schema = z.infer<
  typeof getGoalsGeneralInfo400Schema
>;

export const getGoalsGeneralInfoQueryResponseSchema = z.lazy(
  () => getGoalsGeneralInfo200Schema,
);

export type GetGoalsGeneralInfoQueryResponseSchema = z.infer<
  typeof getGoalsGeneralInfoQueryResponseSchema
>;
