/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { updateResultSchema } from "../updateResultSchema";
import { updateTaskBodySchema } from "../updateTaskBodySchema";
import { z } from "zod";

export const updateTaskPathParamsSchema = z.object({
  task_id: z.string(),
});

export type UpdateTaskPathParamsSchema = z.infer<
  typeof updateTaskPathParamsSchema
>;

export const updateTask200Schema = z.lazy(() => updateResultSchema);

export type UpdateTask200Schema = z.infer<typeof updateTask200Schema>;

export const updateTask400Schema = z.lazy(() => badRequestSchema);

export type UpdateTask400Schema = z.infer<typeof updateTask400Schema>;

export const updateTaskMutationRequestSchema = z.lazy(
  () => updateTaskBodySchema,
);

export type UpdateTaskMutationRequestSchema = z.infer<
  typeof updateTaskMutationRequestSchema
>;

export const updateTaskMutationResponseSchema = z.lazy(
  () => updateTask200Schema,
);

export type UpdateTaskMutationResponseSchema = z.infer<
  typeof updateTaskMutationResponseSchema
>;
