/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { badRequestSchema } from "../badRequestSchema";
import { updateResultSchema } from "../updateResultSchema";
import { updateTaskListOrderBodySchema } from "../updateTaskListOrderBodySchema";
import { z } from "zod";

export const updateTaskListOrder200Schema = z.lazy(() => updateResultSchema);

export type UpdateTaskListOrder200Schema = z.infer<
  typeof updateTaskListOrder200Schema
>;

export const updateTaskListOrder400Schema = z.lazy(() => badRequestSchema);

export type UpdateTaskListOrder400Schema = z.infer<
  typeof updateTaskListOrder400Schema
>;

export const updateTaskListOrderMutationRequestSchema = z.array(
  z.lazy(() => updateTaskListOrderBodySchema),
);

export type UpdateTaskListOrderMutationRequestSchema = z.infer<
  typeof updateTaskListOrderMutationRequestSchema
>;

export const updateTaskListOrderMutationResponseSchema = z.lazy(
  () => updateTaskListOrder200Schema,
);

export type UpdateTaskListOrderMutationResponseSchema = z.infer<
  typeof updateTaskListOrderMutationResponseSchema
>;
