/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@/shared/api/axios-client'
import type { RequestConfig, ResponseErrorConfig } from '@/shared/api/axios-client'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type { DeleteEventMutationResponse, DeleteEvent400 } from '../../models/events/DeleteEvent.ts'
import { useMutation } from '@tanstack/react-query'
import { deleteEventMutationResponseSchema } from '../../zod/events/deleteEventSchema.ts'

export const deleteEventMutationKey = () => [{ url: '/events/{id}' }] as const

export type DeleteEventMutationKey = ReturnType<typeof deleteEventMutationKey>

/**
 * @summary Delete event
 * {@link /events/:id}
 */
export async function deleteEvent(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteEventMutationResponse, ResponseErrorConfig<DeleteEvent400>, unknown>({
    method: 'DELETE',
    url: `/events/${id}`,
    ...requestConfig,
  })
  return deleteEventMutationResponseSchema.parse(res.data)
}

/**
 * @summary Delete event
 * {@link /events/:id}
 */
export function useDeleteEvent<TContext>(
  options: {
    mutation?: UseMutationOptions<DeleteEventMutationResponse, ResponseErrorConfig<DeleteEvent400>, void, TContext> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deleteEventMutationKey()

  return useMutation<DeleteEventMutationResponse, ResponseErrorConfig<DeleteEvent400>, void, TContext>(
    {
      mutationFn: async () => {
        return deleteEvent(config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}